name: App build

on: push

jobs:
  build_with_signing:
    runs-on: macos-latest
    strategy:
      matrix:
        config:
          - scheme: "ppi"
            profile: "PP_BUILD_PROVISION_PROFILE_BASE64"
            plist: "PPI_EXPORT_PLIST"
          # - scheme: "pance"
          #   profile: "PANCE_BUILD_PROVISION_PROFILE_BASE64"
          #   plist: "PANCE_EXPORT_PLIST"
          # - scheme: "medical"
          #   profile: "MEDICAL_BUILD_PROVISION_PROFILE_BASE64"
          #   plist: "MEDICAL_EXPORT_PLIST"
          # - scheme: "mcat"
          #   profile: "MCAT_BUILD_PROVISION_PROFILE_BASE64"
          #   plist: "MCAT_EXPORT_PLIST"

    steps:
      - name: Check Xcode version
        run: /usr/bin/xcodebuild -version

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          pod install

      - name: Install the Apple certificate and provisioning profile for ${{ matrix.config.scheme }}
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_DISTRIBUTION_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets[matrix.config.profile] }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # Decode and import certificate and provisioning profile
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH

          # Create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # Import certificate into keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # Apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      - name: Build archive for ${{ matrix.config.scheme }}
        run: |
          xcodebuild archive \
            -workspace iOS-GitHubActions.xcworkspace \
            -scheme ${{ matrix.config.scheme }} \
            -configuration Release \
            -archivePath /build/${{ matrix.config.scheme }}.xcarchive \
            -sdk iphoneos \
            -destination generic/platform=iOS \
            -allowProvisioningUpdates | xcpretty

      - name: List archive contents (debugging)
        run: ls ${{ github.workspace }}/build/${{ matrix.config.scheme }}.xcarchive

      - name: Export ipa for ${{ matrix.config.scheme }} (verbose)
        env:
          EXPORT_OPTIONS_PLIST: ${{ secrets[matrix.config.plist] }}
        run: |
           EXPORT_OPTS_PATH=$RUNNER_TEMP/ExportOptions.plist
           echo -n "$EXPORT_OPTIONS_PLIST" | base64 --decode -o $EXPORT_OPTS_PATH
           xcodebuild -exportArchive \
            -archivePath /build/${{ matrix.config.scheme }}.xcarchive \
            -exportOptionsPlist $EXPORT_OPTS_PATH \
            -exportPath ${{ github.workspace }}/build/ipa 

      - name: Debug build export path
        run: ls ${{ github.workspace }}/build/ipa

      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.config.scheme }}.ipa
          path: ${{ github.workspace }}/build/ipa/${{ matrix.config.scheme }}.ipa
