name: iOS Build and Archive

on:
  push:
    branches:
      - main
      - 'release/*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        target: 
          - ppi

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          pod install
        working-directory: ./ktp.usurp.ios  # Adjust as needed

      - name: Decrypt and set up distribution certificates and profiles
        run: |
          # Decode the Base64 encoded certificate and provisioning profile
          echo $CERTIFICATE | base64 --decode > cert.p12
          echo $PROVISIONING_PROFILE | base64 --decode > profile.mobileprovision

          # Create a new keychain and import the certificate
          security create-keychain -p actions keychain
          security import cert.p12 -k keychain -P $CERTIFICATE_PASSWORD -T /usr/bin/codesign
          security list-keychains -s keychain
          security set-keychain-settings -t 3600 -u keychain
          security unlock-keychain -p actions keychain
          security set-key-partition-list -S apple-tool:,apple: -s -k actions keychain
          
          # Set the provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
        env:
          CERTIFICATE: ${{ secrets.BUILD_DEVELOP_CERTIFICATE_BASE64 }}  # Base64 encoded distribution certificate
          CERTIFICATE_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}  # Password for the certificate
          PROVISIONING_PROFILE: ${{ secrets.PP_BUILD_PROVISION_PROFILE_BASE64 }}  # Base64 encoded provisioning profile

      - name: Build and Archive
        run: |
          xcodebuild -workspace ktp.usurp.ios/ktp.usurp.ios.xcworkspace \
                     -scheme ${{ matrix.target }} \
                     -configuration Release \
                     -archivePath ${{ github.workspace }}/build/${{ matrix.target }}.xcarchive \
                     SKIP_INSTALL=NO \
                     CODE_SIGNING_REQUIRED=YES \
                     CODE_SIGNING_ALLOWED=YES \
                     -allowProvisioningUpdates

        env:
          ACTION: archive

      - name: Export IPA
        run: |
          # Decode the base64 encoded ExportOptions.plist before export
          echo $EXPORT_OPTIONS_PLIST | base64 --decode > ExportOptions.plist

          xcodebuild -exportArchive \
                     -archivePath ${{ github.workspace }}/build/${{ matrix.target }}.xcarchive \
                     -exportOptionsPlist ExportOptions.plist \
                     -exportPath ${{ github.workspace }}/build/${{ matrix.target }}.ipa
        env:
          EXPORT_OPTIONS_PLIST: ${{ secrets.PPI_EXPORT_PLIST }}  # Base64 encoded ExportOptions.plist

      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}.ipa
          path: ${{ github.workspace }}/build/${{ matrix.target }}.ipa
